### ISSUE TITLE
what command produces the full report?

### ISSUE THREAD

**Issue by tbrasser** [markmcb/storage-scripts#1]
as title says, I tried the 3 scripts and the show a bit of info, but I don't get your full report.

**Comment by markmcb** [comment]
@tbrasser I actually didn't include the script that assembles it all and emails it as it's heavily customized and not very portable, but I probably should include something. The script I have is only about 60 lines, so it shouldn't be much effort. Give me a few days and I'll rework it so that it doesn't have anything hard-coded in and I'll add it to the repository.

**Comment by markmcb** [comment]
Ok, check out the `email_all_reports` script. Still requires some configuration and possibly installing some dependencies.
